# Generated by Django 2.2.10 on 2021-02-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('category', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='a', max_length=10)),
            ],
        ),
    ]
